#!/bin/bash

options=(
    style=round
    width=4.0
    blur_radius=100
    hidpi=on
    active_color="gradient(top_left=0xff89b4fa,bottom_right=0xffcba6f7)"
    inactive_color="gradient(top_left=0xff9399b2,bottom_right=0xff6c7086)"
)

borders "${options[@]}"
