#!/bin/bash

options=(
    style=round
    width=8.0
    blur_radius=100
    hidpi=on
    active_color="gradient(top_left=0xff89b4fa,bottom_right=0xffcba6f7)"
    inactive_color=0x00000000
)

borders "${options[@]}"
